version: 3
services:
  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    networks:
      - getir-network
  book:
    image: book
    container_name: book
    ports:
      - 8081:8081
    build:
      book
    depends_on:
      - mongo
      - eureka-server
      - cloud-gateway
    networks:
      - getir-network

  order:
    image: order
    container_name: order
    ports:
      - 8082:8082
    build:
      order/
    depends_on:
      - mongo
      - eureka-server
      - cloud-gateway
    networks:
      - getir-network
  customer:
    image: customer
    container_name: customer
    ports:
      - 8080:8080
    build:
      customer/
    depends_on:
      - mongo
      - eureka-server
      - cloud-gateway
    networks:
      - getir-network
  statistics:
    image: statistics
    container_name: statistics
    ports:
      - 8083:8083
    build:
      statistics/
    depends_on:
      - mongo
      - eureka-server
      - cloud-gateway
      - order
    networks:
      - getir-network
  cloud-gateway:
    image: cloud-gateway
    container_name: cloud-gateway
    ports:
      - 8000:8000
    build:
      cloud-gateway/
    depends_on:
      - mongo
      - eureka-server
    networks:
      - getir-network
  eureka-server:
    image: eureka-server
    container_name: eureka-server
    ports:
      - 8761:8761
    build:
      eureka-server/
    depends_on:
      - mongo
    networks:
      - getir-network

networks:
  getir-network:
    driver: bridge